### ISSUE TITLE
I never get the key and id followed all the instruction steps

### ISSUE THREAD

**Issue by jesusdp** [AMoo-Miki/homebridge-tuya-lan#150]
pi@raspberrypi:~ $ tuya-lan-find 
 
 I installed the certificate in my iPhone, I have Tuya Smart App with previous installed and setup my smart blinds and kill and open again the Tuya Smart but nothing happen in the terminal. Finally I got the EPIPE error. Please advice.
 
Follow the instructions on https://github.com/AMoo-Miki/homebridge-tuya-lan/wiki/Setup-Instructions
Proxy IP: 10.242.1.99
Proxy Port: 8080

Intercepted certificate request
Intercepted certificate request
Error: { Error: write EPIPE
    at WriteWrap.afterWrite [as oncomplete] (net.js:844:14) errno: 'EPIPE', code: 'EPIPE', syscall: 'write' }
Error: { Error: write EPIPE
    at WriteWrap.afterWrite [as oncomplete] (net.js:844:14) errno: 'EPIPE', code: 'EPIPE', syscall: 'write' }
Error: { Error: write EPIPE
    at WriteWrap.afterWrite [as oncomplete] (net.js:844:14) errno: 'EPIPE', code: 'EPIPE', syscall: 'write' }
Error: { Error: write EPIPE
    at WriteWrap.afterWrite [as oncomplete] (net.js:844:14) errno: 'EPIPE', code: 'EPIPE', syscall: 'write' }

**Comment by iRayanKhan** [comment]
See [this issue](https://github.com/AMoo-Miki/homebridge-tuya-lan/issues/147)

**Comment by jesusdp** [comment]
@iRayanKhan Thanks for the help. I will try with another app to see if I can get the key and id.

**Comment by levieli70** [comment]
with smart life i get these errors:

Error: { Error: socket hang up
    at TLSSocket.onSocketClose (_tls_wrap.js:743:23)
    at TLSSocket.emit (events.js:193:15)
    at _handle.close (net.js:609:12)
    at Socket.done (_tls_wrap.js:390:7)
    at Object.onceWrapper (events.js:276:13)
    at Socket.emit (events.js:188:13)
    at TCP._handle.close (net.js:609:12) code: 'ECONNRESET' }
Error: { Error: socket hang up
    at TLSSocket.onSocketClose (_tls_wrap.js:743:23)
    at TLSSocket.emit (events.js:193:15)
    at _handle.close (net.js:609:12)
    at Socket.done (_tls_wrap.js:390:7)
    at Object.onceWrapper (events.js:276:13)
    at Socket.emit (events.js:188:13)
    at TCP._handle.close (net.js:609:12) code: 'ECONNRESET' }
Error: { Error: socket hang up
    at TLSSocket.onSocketClose (_tls_wrap.js:743:23)
    at TLSSocket.emit (events.js:193:15)
    at _handle.close (net.js:609:12)
    at Socket.done (_tls_wrap.js:390:7)
    at Object.onceWrapper (events.js:276:13)
    at Socket.emit (events.js:188:13)
    at TCP._handle.close (net.js:609:12) code: 'ECONNRESET' }

**Comment by AntlerDM** [comment]
I am getting the same "Error: { Error: socket hang up" as above. Also, after launching the Tuya Smart app, an error is displayed in the app that says 

"Network is unavailable,

**Comment by AntlerDM** [comment]
Full error is...

`Intercepted certificate request
  Error: { Error: socket hang up
      at TLSSocket.onSocketClose (_tls_wrap.js:764:23)
      at TLSSocket.emit (events.js:203:15)
      at _handle.close (net.js:607:12)
      at Socket.done (_tls_wrap.js:388:7)
      at Object.onceWrapper (events.js:286:20)
      at Socket.emit (events.js:198:13)
      at TCP._handle.close (net.js:607:12) code: 'ECONNRESET' }`

Which seems to be repeated for each device (guessing)

**Comment by earlywaff** [comment]
AntlerDM <Do everything as you do. But change the application to Ucomen Home!

**Comment by AntlerDM** [comment]
Thanks for the suggestion, but it did not help. Same error messages in the console.

Installed Ucomen Home v. 1.12 (current version)

**Comment by AntlerDM** [comment]
I started from scratch and was able to get it to work, finally.

- I changed the IP Address of my HOOBS (in case there was a network issue).
- I changed the tuya-lan-find listening port to 8888 (using nano to replace '8080' with '8888' in cli.js.
- I ran tuya-lan-find in an ssh window from macOS Terminal.app instead of using the 'Terminal' within HOOBS interface.
- Used Ucomen Home app version 1.12

Not sure which of these changes solved the problem. But I have 19 device IDs and Keys to start adding to HHOBS.

**Comment by earlywaff** [comment]
Were you able to add devices to homebridge? 
tell me the version of homebrige, node js, and npm.

**Comment by AntlerDM** [comment]
A few simple plugs, yes. RGBW Bulbs are not working, but I have not given up yet.

Woking:
CE Smart Home,  WiFi Smart Outlet (indoor) ([link](https://www.cesmarthome.com/LA-2-W3.html))
Prime Wire and Cable, WiFi Smart Outlet (Outdoor) ([link](https://primewirecable.com/collections/smart-home-devices/products/2-outlet-black-outdoor-wi-fi-remote-control))

Not Working:
Globe Electric, WiFi Smart Bulb (RGB, Tuneable White) ([link](https://globe-electric.com/en/product/globe-electric-wi-fi-smart-60w-equivalent-multicolor-changing-rgb-tunable-white-dimmable-frosted-led-light-bulb-no-hub-required-a19-e26-base-2-pack34207/))
CE Smart Home, WiFi Smart Power Strip (5 plug) ([link](https://www.cesmarthome.com/LTS-6A-W5.html))

Running current version of HOOBS (3.1.20) on a RaspberryPi 4b (4GB RAM).
Homebridge Version 0.4.50 | Node Version 10.18.0 | homebridge-tuya-lan Version 1.4.0

**Comment by iRayanKhan** [comment]
I feel like making a new repo of this plugin and merging all the fixes into it and keep it active. Would any be opposed to this? 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by TheHomekitWayFinder** [comment]
@iRayanKhan that sounds like a good idea as @AMoo-Miki is very regularly not online and therefore we are all having so many issues and once someone finds a fix he’s never online to accept a pull request. Just make sure you give credit to @AMoo-Miki and this repo along with tuyAPI

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by iRayanKhan** [comment]
Ofc credit will be given. I’ll start work on this in a few hours. Repo being made now

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by TheHomekitWayFinder** [comment]
@iRayanKhan sounds good. Just out of interest do you have any experience with working on the Tuya protocol and the HAP specification or not, just wondering for help with issues

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by iRayanKhan** [comment]
Yes, I currently maintain another HAP plugin (homebridge-chamberlain) 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by iRayanKhan** [comment]
I just pushed a small bit of changes, for the ID"s and other accessories those will be merged in later tonight.

**Comment by mitch7391** [comment]
@iRayanKhan is it at a stage where we can start testing it? I’m getting very impatient with this plug-in waiting for fixes on this plug-in haha I was able to finally discover my Arlec smart bulb with the rc-12, but I still cannot issue commands.

**Comment by iRayanKhan** [comment]
Yes it is currently on my GitHub page, I need to publish it to NPM. Issue #-3 on there shows how to install it if you don't know how to git clone. I found that using the Ucoven or Ucomen home app can still generate the ID's, and the original Tuya API has been deprecated, and this app hasn't been updated to support it, which is good. 

Also I have noticed closing the app/disabling wi-fi on your device with the certificate afterwards help generate the ID's for me
